import {
  MessageSquare,
  Hash,
  FileText,
} from "lucide-react";
import { StatCard } from "@/components/dashboard";
import {
  getChannels,
  getRecentMessages,
  getMessageTemplates,
  getCommunicationStats,
  messageTypeLabels,
  priorityClasses,
  channelTypeLabels,
} from "@/lib/communication-hub-data";

const stats = getCommunicationStats();
const channels = getChannels();
const recentMessages = getRecentMessages(7);
const templates = getMessageTemplates();

const dateFormatter = new Intl.DateTimeFormat("it-IT", {
  day: "2-digit",
  month: "short",
  hour: "2-digit",
  minute: "2-digit",
});

export default function CommunicationPage() {
  return (
    <div className="space-y-8">
      <section>
        <p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-700">
          Comunicazione
        </p>
        <h1 className="mt-2 text-3xl font-bold tracking-tight text-emerald-950 sm:text-4xl">
          Hub comunicazione multi-stakeholder
        </h1>
        <p className="mt-3 max-w-3xl text-sm leading-7 text-emerald-950/70 sm:text-base">
          Canali strutturati, messaggi contestuali con dati di campo, template automatici e audit trail per sostituire WhatsApp nella cooperativa.
        </p>
      </section>

      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Canali attivi" value={String(stats.totalChannels)} change="Cooperativa, coltura, zona, ruolo" trend="up" />
        <StatCard label="Messaggi questa settimana" value={String(stats.totalMessagesThisWeek)} change={`${stats.autoGeneratedPercent}% automatici`} trend="up" />
        <StatCard label="Non letti" value={String(stats.unreadMessages)} change={stats.criticalUnread > 0 ? `${stats.criticalUnread} urgenti` : "Nessuno urgente"} trend={stats.unreadMessages > 5 ? "down" : "neutral"} />
        <StatCard label="Tempo risposta medio" value={`${stats.avgResponseTimeHours}h`} change="Dalla ricezione alla lettura" trend="up" />
      </section>

      <section className="grid gap-6 xl:grid-cols-[0.4fr_0.6fr]">
        {/* Channels */}
        <article className="rounded-3xl border border-emerald-950/10 bg-white/90 p-6 shadow-sm shadow-emerald-950/5">
          <div className="flex items-center gap-3">
            <div className="rounded-2xl bg-emerald-100 p-3 text-emerald-800">
              <Hash className="h-6 w-6" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-emerald-950">Canali</h2>
              <p className="text-sm text-emerald-950/65">Gruppi tematici della cooperativa</p>
            </div>
          </div>
          <div className="mt-6 space-y-2">
            {channels.map((ch) => (
              <div key={ch.id} className={`rounded-2xl border p-4 ${ch.unreadCount > 0 ? "border-emerald-700/30 bg-emerald-50" : "border-emerald-950/10 bg-[#f7f4ec]"}`}>
                <div className="flex items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    {ch.isPinned && <span className="text-amber-500">📌</span>}
                    <p className="text-sm font-semibold text-emerald-950">{ch.name}</p>
                  </div>
                  {ch.unreadCount > 0 && (
                    <span className="flex h-5 min-w-[20px] items-center justify-center rounded-full bg-emerald-700 px-1.5 text-xs font-bold text-white">{ch.unreadCount}</span>
                  )}
                </div>
                <div className="mt-1 flex items-center justify-between text-xs text-emerald-950/55">
                  <span>{channelTypeLabels[ch.type]} · {ch.memberCount} membri</span>
                </div>
              </div>
            ))}
          </div>
        </article>

        {/* Recent Messages */}
        <article className="rounded-3xl border border-emerald-950/10 bg-white/90 p-6 shadow-sm shadow-emerald-950/5">
          <div className="flex items-center gap-3">
            <div className="rounded-2xl bg-sky-100 p-3 text-sky-700">
              <MessageSquare className="h-6 w-6" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-emerald-950">Messaggi recenti</h2>
              <p className="text-sm text-emerald-950/65">Feed unificato da tutti i canali</p>
            </div>
          </div>
          <div className="mt-6 space-y-3">
            {recentMessages.map((msg) => {
              const channel = channels.find((c) => c.id === msg.channelId);
              return (
                <div key={msg.id} className="rounded-2xl border border-emerald-950/10 bg-[#f7f4ec] p-4">
                  <div className="flex flex-wrap items-start justify-between gap-2">
                    <div className="flex items-center gap-2">
                      <span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${priorityClasses[msg.priority]}`}>
                        {msg.priority}
                      </span>
                      <span className="rounded-full bg-white px-2 py-0.5 text-xs text-emerald-950/55 shadow-sm">
                        {messageTypeLabels[msg.type]}
                      </span>
                    </div>
                    <span className="text-xs text-emerald-950/50">{dateFormatter.format(new Date(msg.sentAt))}</span>
                  </div>
                  <h3 className="mt-2 text-sm font-semibold text-emerald-950">{msg.subject}</h3>
                  <p className="mt-1 text-sm text-emerald-950/65 line-clamp-2">{msg.body}</p>
                  <div className="mt-2 flex flex-wrap items-center gap-3 text-xs text-emerald-950/50">
                    <span>👤 {msg.senderName}</span>
                    <span>#{channel?.name ?? msg.channelId}</span>
                    <span>👁 {msg.readByCount}/{msg.totalRecipients}</span>
                    {msg.hasAttachment && <span>📎 {msg.attachmentName}</span>}
                    {msg.isAutoGenerated && <span className="rounded bg-emerald-100 px-1.5 py-0.5 text-emerald-700">Auto</span>}
                  </div>
                </div>
              );
            })}
          </div>
        </article>
      </section>

      {/* Templates */}
      <article className="rounded-3xl border border-emerald-950/10 bg-white/90 p-6 shadow-sm shadow-emerald-950/5">
        <div className="flex items-center gap-3">
          <div className="rounded-2xl bg-violet-100 p-3 text-violet-700">
            <FileText className="h-6 w-6" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-emerald-950">Template messaggi</h2>
            <p className="text-sm text-emerald-950/65">Modelli con variabili auto-compilate dai dati della piattaforma</p>
          </div>
        </div>
        <div className="mt-6 space-y-3">
          {templates.map((tpl) => (
            <div key={tpl.id} className="rounded-2xl border border-emerald-950/10 bg-[#f7f4ec] p-4">
              <div className="flex items-center justify-between gap-2">
                <p className="text-sm font-semibold text-emerald-950">{tpl.name}</p>
                <span className="rounded-full bg-white px-2.5 py-1 text-xs text-emerald-950/55 shadow-sm">{messageTypeLabels[tpl.type]}</span>
              </div>
              <p className="mt-1 text-sm text-emerald-950/65">{tpl.subject}</p>
              <p className="mt-2 text-xs text-emerald-950/50 font-mono bg-white/80 rounded-lg p-2">{tpl.body}</p>
              <div className="mt-2 flex flex-wrap gap-1">
                {tpl.variables.map((v) => (
                  <span key={v} className="rounded bg-emerald-100 px-1.5 py-0.5 text-xs text-emerald-700 font-mono">{`{${v}}`}</span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </article>
    </div>
  );
}
