"use client";

import {
  Activity,
  BarChart3,
  Bot,
  BrainCircuit,
  Bug,
  CloudSun,
  Cog,
  Crosshair,
  Dices,
  Droplets,
  FileOutput,
  Gauge,
  Globe,
  Handshake,
  Home,
  Landmark,
  Leaf,
  Link2,
  Lock,
  MessageSquare,
  Network,
  Newspaper,
  Package,
  QrCode,
  Radio,
  Rocket,
  Route,
  Satellite,
  ScanSearch,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Store,
  TestTubes,
  Tractor,
  TrendingUp,
  Trees,
  Users,
  UsersRound,
  Wallet,
} from "lucide-react";
import { DashboardShell } from "@/components/dashboard";

const iconProps = { className: "h-5 w-5", "aria-hidden": true } as const;

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DashboardShell
      brand="AgriRomagna"
      items={[
        {
          label: "Panoramica",
          href: "/dashboard",
          icon: <Home {...iconProps} />,
          section: "Core workflows",
          keywords: ["home", "overview", "dashboard"],
          priority: true,
        },
        {
          label: "Campi",
          href: "/dashboard/fields",
          icon: <Trees {...iconProps} />,
          section: "Core workflows",
          keywords: ["appezzamenti", "catasto", "field"],
          priority: true,
        },
        {
          label: "Meteo & rischi",
          href: "/dashboard/weather",
          icon: <CloudSun {...iconProps} />,
          section: "Core workflows",
          keywords: ["rain", "clima", "forecast"],
          priority: true,
        },
        {
          label: "Raccolta",
          href: "/dashboard/harvest",
          icon: <Tractor {...iconProps} />,
          section: "Core workflows",
          keywords: ["harvest", "crew", "volumi"],
          priority: true,
        },
        {
          label: "Logistica",
          href: "/dashboard/logistics",
          icon: <Route {...iconProps} />,
          section: "Core workflows",
          keywords: ["route", "fleet", "ritiri"],
          priority: true,
        },
        {
          label: "Tracciabilità",
          href: "/dashboard/traceability",
          icon: <QrCode {...iconProps} />,
          section: "Core workflows",
          keywords: ["lotto", "dpp", "qr"],
          priority: true,
        },
        {
          label: "Vendita diretta",
          href: "/dashboard/marketplace",
          icon: <ShoppingBag {...iconProps} />,
          section: "Core workflows",
          keywords: ["catalogo", "orders", "ecommerce"],
          priority: true,
        },
        {
          label: "Cooperativa",
          href: "/dashboard/cooperative",
          icon: <UsersRound {...iconProps} />,
          section: "Operazioni",
          keywords: ["members", "coop"],
        },
        {
          label: "Conformità",
          href: "/dashboard/compliance",
          icon: <ShieldCheck {...iconProps} />,
          section: "Operazioni",
          keywords: ["audit", "documents", "compliance"],
        },
        {
          label: "Forza lavoro",
          href: "/dashboard/workforce",
          icon: <Users {...iconProps} />,
          section: "Operazioni",
          keywords: ["shift", "workers"],
        },
        {
          label: "Attrezzature",
          href: "/dashboard/equipment",
          icon: <Cog {...iconProps} />,
          section: "Operazioni",
          keywords: ["maintenance", "tractor"],
        },
        {
          label: "Comunicazione",
          href: "/dashboard/communication",
          icon: <MessageSquare {...iconProps} />,
          section: "Operazioni",
          keywords: ["chat", "alerts", "team"],
        },
        {
          label: "Mobile campo",
          href: "/dashboard/mobile",
          icon: <Smartphone {...iconProps} />,
          section: "Operazioni",
          keywords: ["field app", "mobile"],
        },
        {
          label: "Analytics",
          href: "/dashboard/analytics",
          icon: <Gauge {...iconProps} />,
          section: "Insight & AI",
          keywords: ["telemetry", "metrics"],
        },
        {
          label: "Insight Engine",
          href: "/dashboard/insights",
          icon: <Sparkles {...iconProps} />,
          section: "Insight & AI",
          keywords: ["insights", "recommendations"],
        },
        {
          label: "Consulente AI",
          href: "/dashboard/advisor",
          icon: <Bot {...iconProps} />,
          section: "Insight & AI",
          keywords: ["advisor", "chat", "recommendations"],
        },
        {
          label: "Anomalie & previsioni",
          href: "/dashboard/anomaly-detection",
          icon: <ScanSearch {...iconProps} />,
          section: "Insight & AI",
          keywords: ["forecast", "alerts"],
        },
        {
          label: "Intelligenza",
          href: "/dashboard/intelligence",
          icon: <Activity {...iconProps} />,
          section: "Insight & AI",
          keywords: ["fabric", "intelligence"],
        },
        {
          label: "Previsioni resa",
          href: "/dashboard/yield-prediction",
          icon: <TrendingUp {...iconProps} />,
          section: "Insight & AI",
          keywords: ["yield", "prediction"],
        },
        {
          label: "Benchmarking",
          href: "/dashboard/benchmarking",
          icon: <BarChart3 {...iconProps} />,
          section: "Insight & AI",
          keywords: ["benchmark", "compare"],
        },
        {
          label: "Satellitare",
          href: "/dashboard/satellite",
          icon: <Satellite {...iconProps} />,
          section: "Sostenibilità & rischio",
          keywords: ["ndvi", "map", "copernicus"],
        },
        {
          label: "Carbonio",
          href: "/dashboard/carbon",
          icon: <Leaf {...iconProps} />,
          section: "Sostenibilità & rischio",
          keywords: ["co2", "carbon"],
        },
        {
          label: "ESG & Impatto",
          href: "/dashboard/esg",
          icon: <Leaf {...iconProps} />,
          section: "Sostenibilità & rischio",
          keywords: ["impact", "esg"],
        },
        {
          label: "Gestione idrica",
          href: "/dashboard/water",
          icon: <Droplets {...iconProps} />,
          section: "Sostenibilità & rischio",
          keywords: ["irrigation", "water"],
        },
        {
          label: "Allerta fitosanitaria",
          href: "/dashboard/pest-warning",
          icon: <Bug {...iconProps} />,
          section: "Sostenibilità & rischio",
          keywords: ["disease", "warning"],
        },
        {
          label: "Assicurazione",
          href: "/dashboard/insurance",
          icon: <Shield {...iconProps} />,
          section: "Sostenibilità & rischio",
          keywords: ["policy", "claims"],
        },
        {
          label: "Salute suolo",
          href: "/dashboard/soil-health",
          icon: <Globe {...iconProps} />,
          section: "Sostenibilità & rischio",
          keywords: ["soil", "analysis"],
        },
        {
          label: "Radar normativo",
          href: "/dashboard/regulatory",
          icon: <Newspaper {...iconProps} />,
          section: "Sostenibilità & rischio",
          keywords: ["laws", "updates", "regole"],
        },
        {
          label: "Spray optimizer",
          href: "/dashboard/spray-optimizer",
          icon: <Crosshair {...iconProps} />,
          section: "Sostenibilità & rischio",
          keywords: ["spray", "dosage"],
        },
        {
          label: "Sensori IoT",
          href: "/dashboard/iot",
          icon: <Radio {...iconProps} />,
          section: "Piattaforma & rete",
          keywords: ["sensor", "devices"],
        },
        {
          label: "Filiera",
          href: "/dashboard/supply-chain",
          icon: <Package {...iconProps} />,
          section: "Piattaforma & rete",
          keywords: ["supply chain", "lots"],
        },
        {
          label: "Governance",
          href: "/dashboard/governance",
          icon: <Landmark {...iconProps} />,
          section: "Piattaforma & rete",
          keywords: ["vote", "proposals"],
        },
        {
          label: "Interoperabilità",
          href: "/dashboard/interoperability",
          icon: <FileOutput {...iconProps} />,
          section: "Piattaforma & rete",
          keywords: ["fmis", "export", "api"],
        },
        {
          label: "Catena conformità",
          href: "/dashboard/compliance-chain",
          icon: <Link2 {...iconProps} />,
          section: "Piattaforma & rete",
          keywords: ["chain", "audit"],
        },
        {
          label: "Data Marketplace",
          href: "/dashboard/data-marketplace",
          icon: <Store {...iconProps} />,
          section: "Piattaforma & rete",
          keywords: ["data products", "datasets"],
        },
        {
          label: "Knowledge Graph",
          href: "/dashboard/knowledge-graph",
          icon: <BrainCircuit {...iconProps} />,
          section: "Piattaforma & rete",
          keywords: ["graph", "knowledge"],
        },
        {
          label: "Federazione",
          href: "/dashboard/federation",
          icon: <Network {...iconProps} />,
          section: "Piattaforma & rete",
          keywords: ["multi coop", "federation"],
        },
        {
          label: "Accessi & Ruoli",
          href: "/dashboard/rbac",
          icon: <Lock {...iconProps} />,
          section: "Piattaforma & rete",
          keywords: ["rbac", "roles"],
        },
        {
          label: "Commerciale",
          href: "/dashboard/commercial",
          icon: <Handshake {...iconProps} />,
          section: "Sperimentazione",
          keywords: ["sales", "crm"],
        },
        {
          label: "Simulatore",
          href: "/dashboard/simulator",
          icon: <Dices {...iconProps} />,
          section: "Sperimentazione",
          keywords: ["scenario", "what if"],
        },
        {
          label: "Test & CI/CD",
          href: "/dashboard/test-harness",
          icon: <TestTubes {...iconProps} />,
          section: "Sperimentazione",
          keywords: ["tests", "ci"],
        },
        {
          label: "Moonshots",
          href: "/dashboard/moonshots",
          icon: <Rocket {...iconProps} />,
          section: "Sperimentazione",
          keywords: ["vision", "future"],
        },
      ]}
    >
      {children}
    </DashboardShell>
  );
}
